[patterns]
num_word_f = "(one|two|three|four|five|six|seven|eight|nine|\\d)"
num_word_r = "(eno|owt|eerht|ruof|evif|xis|neves|thgie|enin|\\d)"
game = "(?<=Game )\\d+"
digit_color = "(\\d+) (red|green|blue)"
non_digit = "[^\\d.]"
number = "\\d+"
gear = "\\*"
map_node = "\\b[A-Z]{3}\\b"
s = "S"
galaxy = "#"
broken_window = "#+"
alphanumeric = "\\w+"
trench = "([UDRL]) (\\d+) \(\\#([a-f0-9]{5})([0-4])\\)"